from pathlib import Path
from playwright.sync_api import sync_playwright,expect
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    page=browser.new_page(viewport={'width':390,'height':844})
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://localhost:5173');page.wait_for_load_state('networkidle')
    page.get_by_role('button',name='선수 맞히기 시작').click()
    def state():return page.evaluate("JSON.parse(localStorage.getItem('bluewings-player-game-v4'))")
    def answer():
        g=state();r=g['rounds'][g['index']];page.locator('.choices button').nth(r['choices'].index(r['playerId'])).click()
    answer();expect(page.locator('.nohint-badge')).to_be_visible();expect(page.locator('.combo-popup')).to_have_count(0)
    page.get_by_role('button',name='다음 선수',exact=True).click()
    page.get_by_role('button',name='추가 힌트').click();answer()
    expect(page.locator('.combo-popup')).to_contain_text('2 COMBO')
    expect(page.locator('.nohint-badge')).to_have_count(0)
    page.wait_for_timeout(2400);expect(page.locator('.combo-popup')).to_have_count(0)
    page.reload();expect(page.locator('.combo-popup')).to_have_count(0)
    page.get_by_role('button',name='다음 선수',exact=True).click()
    g=state();r=g['rounds'][2];wrong=next(id for id in r['choices'] if id!=r['playerId'])
    page.locator('.choices button').nth(r['choices'].index(wrong)).click()
    expect(page.locator('.combo-counter')).to_contain_text('현재 0콤보')
    answer();expect(page.locator('.nohint-badge')).to_be_visible()
    expect(page.locator('.combo-popup')).to_have_count(0)
    page.get_by_role('button',name='다음 선수',exact=True).click()
    for i in range(3,10):
        answer()
        if i==4:expect(page.locator('.combo-popup')).to_contain_text('2 COMBO')
        page.get_by_role('button',name='결과 보기' if i==9 else '다음 선수',exact=True).click()
    expect(page.locator('.achievement-summary')).to_contain_text('최대 7콤보')
    expect(page.locator('.achievement-summary')).to_contain_text('노힌트 9명')
    expect(page.locator('.badge-roster article')).to_have_count(9)
    expect(page.locator('.badge-roster')).to_contain_text('재도전')
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    expect(page.get_by_role('button',name='이미지 저장')).to_be_enabled(timeout=60000)
    Path('test-results').mkdir(exist_ok=True)
    with page.expect_download() as dl:page.get_by_role('button',name='이미지 저장').click()
    dl.value.save_as('test-results/combo-report.png')
    page.screenshot(path='test-results/combo-result.png',full_page=True)
    page.reload();expect(page.locator('.badge-roster article')).to_have_count(9)
    assert not errors,errors
    print('PASS: combo popup/reset/refresh, hints, retry badge, results, PNG, mobile overflow')
    browser.close()
