import roster from './players.json';
export type Player = typeof roster[number];
export const players: Player[] = roster;
export const positionNames: Record<string,string> = {GK:'골키퍼',DF:'수비수',MF:'미드필더',FW:'공격수'};
export type Hint = 'photo' | 'age' | 'height' | 'position';
export const FACE_GRID = 8;
export const FACE_TILES = FACE_GRID * FACE_GRID;
export function tileOrder(){const all=Array.from({length:FACE_TILES},(_,i)=>i);const facial=all.filter(i=>Math.floor(i/FACE_GRID)>=3&&Math.floor(i/FACE_GRID)<=5&&i%FACE_GRID>=1&&i%FACE_GRID<=6);return [...shuffle(facial),...shuffle(all.filter(i=>!facial.includes(i)))];}
export type Round = { playerId: string; choices: string[]; wrongIds:string[]; photoStage: number; tileOrder:number[]; hints: Hint[]; selected: string | null; complete: boolean; earned: number; timedOut: boolean };
export type Game = { rounds: Round[]; index: number; duration: number; remaining: number; deadline: number | null; finished: boolean; date: string; id:string; name:string; startedAt:number; completedAt:number|null; endedAt:number|null };
export function shuffle<T>(items:T[]):T[]{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function age(birthday:string,date:string){const birth=birthday.split('-').map(Number),today=date.split('-').map(Number);return today[0]-birth[0]-(today[1]<birth[1]||(today[1]===birth[1]&&today[2]<birth[2])?1:0);}
export function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function availableScore(round:Round){return Math.max(10,100-(round.hints.length+round.wrongIds.length)*15);}
export function availableHints(round:Round):Hint[]{if(round.complete)return [];return [...(round.photoStage<FACE_TILES-1?['photo' as const]:[]),...(['age','height','position'] as Hint[]).filter(h=>!round.hints.includes(h))];}
export function addHint(round:Round,random=Math.random()):Round{const candidates=availableHints(round);if(!candidates.length)return round;const hint=candidates[Math.min(candidates.length-1,Math.floor(Math.max(0,random)*candidates.length))];return {...round,hints:[...round.hints,hint],photoStage:round.photoStage+(hint==='photo'?1:0)};}
export function submit(round:Round,id:string):Round{if(round.complete||!round.choices.includes(id))return round;if(id===round.playerId)return {...round,selected:id,complete:true,earned:availableScore(round)};const wrongIds=[...round.wrongIds,id];const pool=players.filter(p=>p.id!==round.playerId&&!round.choices.includes(p.id)&&!wrongIds.includes(p.id));const replacement=shuffle(pool)[0];const choices=replacement?round.choices.map(v=>v===id?replacement.id:v):round.choices.filter(v=>v!==id);return {...round,wrongIds,choices};}
export function remainingTime(game:Game,now=Date.now()){return game.deadline===null?game.remaining:Math.max(0,Math.ceil((game.deadline-now)/1000));}
export function elapsedMs(game:Game,now=Date.now()){return Math.max(0,(game.completedAt??game.endedAt??now)-game.startedAt);}
export function completeRound(game:Game,round:Round,at=Date.now()):Game{if(game.rounds[game.index].complete)return game;const rounds=game.rounds.map((r,i)=>i===game.index?round:r);if(!round.complete)return {...game,rounds};return {...game,rounds,deadline:null,remaining:remainingTime(game,at),completedAt:rounds.every(r=>r.complete)?Math.max(game.startedAt,at):null};}
export type RecordEntry={id:string;name:string;count:number;score:number;elapsed:number;date:string};
export function gameRecord(game:Game):RecordEntry|null{if(game.completedAt===null||!game.rounds.every(r=>r.complete))return null;return {id:game.id,name:game.name,count:game.rounds.length,score:game.rounds.reduce((sum,r)=>sum+r.earned,0),elapsed:elapsedMs(game),date:game.date};}
export function rankRecords(records:RecordEntry[],count:number){return records.filter(r=>r.count===count).sort((a,b)=>b.score-a.score||a.elapsed-b.elapsed||a.id.localeCompare(b.id));}
export function formatElapsed(ms:number){return `${(ms/1000).toFixed(2)}초`;}
export function newGame(count:number,name="게스트"):Game {const duration=30;const startedAt=Date.now();const chosen=shuffle(players).slice(0,count);return {rounds:chosen.map(p=>{const similar=players.filter(q=>q.id!==p.id&&q.position===p.position);const distractors=shuffle(similar.length>=3?similar:players.filter(q=>q.id!==p.id)).slice(0,3);return {playerId:p.id,choices:shuffle([p.id,...distractors.map(q=>q.id)]),wrongIds:[],photoStage:0,tileOrder:tileOrder(),hints:[],selected:null,complete:false,earned:0,timedOut:false};}),index:0,duration,remaining:duration,deadline:duration?Date.now()+duration*1000:null,finished:false,date:localDate(),id:crypto.randomUUID(),name:name.trim()||"게스트",startedAt,completedAt:null,endedAt:null};}
export function validGame(value:unknown):value is Game{if(!value||typeof value!=='object')return false;const g=value as Game;if(!Array.isArray(g.rounds)||!g.rounds.length||g.rounds.length>players.length||!Number.isInteger(g.index)||g.index<0||g.index>=g.rounds.length||g.duration!==30||!Number.isFinite(g.remaining)||g.remaining<0||(g.deadline!==null&&!Number.isFinite(g.deadline))||typeof g.id!=='string'||typeof g.name!=='string'||!Number.isFinite(g.startedAt)||g.startedAt<=0||(g.completedAt!==null&&(!Number.isFinite(g.completedAt)||g.completedAt<g.startedAt))||(g.endedAt!==null&&(!Number.isFinite(g.endedAt)||g.endedAt<g.startedAt))||typeof g.finished!=='boolean'||!/^\d{4}-\d{2}-\d{2}$/.test(g.date))return false;return new Set(g.rounds.map(r=>r.playerId)).size===g.rounds.length&&g.rounds.every(r=>players.some(p=>p.id===r.playerId)&&Array.isArray(r.choices)&&r.choices.length>=1&&r.choices.length<=4&&new Set(r.choices).size===r.choices.length&&r.choices.includes(r.playerId)&&r.choices.every(id=>players.some(p=>p.id===id))&&Array.isArray(r.wrongIds)&&new Set(r.wrongIds).size===r.wrongIds.length&&r.wrongIds.every(id=>id!==r.playerId&&!r.choices.includes(id)&&players.some(p=>p.id===id))&&Number.isInteger(r.photoStage)&&r.photoStage>=0&&r.photoStage<FACE_TILES&&Array.isArray(r.tileOrder)&&r.tileOrder.length===FACE_TILES&&new Set(r.tileOrder).size===FACE_TILES&&r.tileOrder.every(t=>Number.isInteger(t)&&t>=0&&t<FACE_TILES)&&Array.isArray(r.hints)&&r.hints.every(h=>['photo','age','height','position'].includes(h))&&r.hints.filter(h=>h==='photo').length===r.photoStage&&['age','height','position'].every(h=>r.hints.filter(v=>v===h).length<=1)&&typeof r.complete==='boolean'&&typeof r.timedOut==='boolean'&&(r.selected===null||r.choices.includes(r.selected))&&Number.isFinite(r.earned)&&r.earned>=0&&r.earned<=100);}
