import { assetPath } from './assets';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Eye, Lightbulb, Pause, Play, Search, Trophy, Users, Volume2, VolumeX, X, Download, RotateCcw } from 'lucide-react';
import { players, positionNames, age, localDate, newGame, validGame, remainingTime, availableScore, availableHints, addHint, submit, FACE_GRID, FACE_TILES, type Player, type Game, type Round } from './player-game';
import './player-style.css';
const byId = new Map(players.map(p=>[p.id,p]));
function read(key:string):unknown {try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}}
let audio:AudioContext|undefined;
function unlock(){try{audio??=new AudioContext();void audio.resume();}catch{/* 시각 알림으로 진행 */}}
function beep(correct:boolean){try{unlock();if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=correct?880:330;g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);o.start();o.stop(audio.currentTime+.25);}catch{/* 오디오 미지원 */}}
function PlayerPhoto({player,stage,tileOrder=[],full=false}:{player:Player;stage:number;tileOrder?:number[];full?:boolean}){
 const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[player.id]);const f=player.face;
 const opened=new Set(tileOrder.slice(0,stage+1));
 return <div className={`player-photo ${full?'full-photo':''}`}>
 {failed?<div className="photo-fallback"><Users size={44}/><strong>사진을 불러오지 못했어요</strong><span>추가 힌트의 선수 정보를 이용해 주세요.</span></div>:full?<img src={assetPath(player.image)} alt="선수 전체 사진" onError={()=>setFailed(true)} className="whole-player"/>:<div className="face-window"><img src={assetPath(player.image)} alt="작은 칸으로 일부만 공개된 선수 얼굴" onError={()=>setFailed(true)} style={{width:`${f.imageWidth/f.size*100}%`,left:`${-f.x/f.size*100}%`,top:`${-f.y/f.size*100}%`}}/><div className="face-grid" aria-hidden="true" style={{gridTemplateColumns:`repeat(${FACE_GRID},1fr)`}}>{Array.from({length:FACE_TILES},(_,i)=><span key={i} className={`face-cell ${opened.has(i)?'opened':'covered'}`}>{!opened.has(i)&&<i>·</i>}</span>)}</div></div>}
 {!full&&<span className="photo-tag"><Eye size={14}/>얼굴 {opened.size}/{FACE_TILES}칸 공개</span>}</div>;
}
function Profile({player,date}:{player:Player;date:string}){return <div className="profile-chips"><span>{positionNames[player.position]}</span><span>만 {age(player.birthday,date)}세</span><span>{player.height}cm</span><span>등번호 {player.number}</span></div>;}
export default function PlayerApp(){
 const [game,setGame]=useState<Game|null>(()=>{const saved=read('bluewings-player-game-v2');return validGame(saved)?saved:null;});
 const [page,setPage]=useState<'home'|'game'|'roster'>(()=>game?'game':'home');
 const [settings,setSettings]=useState(()=>{const s=read('bluewings-player-settings-v1') as {count?:number;duration?:number;sound?:boolean}|null;return {count:[10,20,40].includes(s?.count??0)?s!.count!:10,duration:[0,30,60,90].includes(s?.duration??-1)?s!.duration!:60,sound:typeof s?.sound==='boolean'?s.sound:true};});
 const [now,setNow]=useState(Date.now());const [message,setMessage]=useState('');const [filter,setFilter]=useState('ALL');const [search,setSearch]=useState('');const endedSound=useRef('');
 useEffect(()=>{try{localStorage.setItem('bluewings-player-game-v2',JSON.stringify(game));localStorage.setItem('bluewings-player-settings-v1',JSON.stringify(settings));}catch{setMessage('브라우저 저장 공간이 부족해 진행 상태를 저장하지 못했습니다.');}},[game,settings]);
 useEffect(()=>{if(!game||!game.deadline||game.finished)return;const tick=()=>setNow(Date.now());tick();const timer=setInterval(tick,200);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);};},[game?.deadline,game?.finished]);
 const round=game?.rounds[game.index];const player=round?byId.get(round.playerId):undefined;const seconds=game?remainingTime(game,now):0;
 useEffect(()=>{if(!game||!round||round.complete||game.finished||game.deadline===null||seconds>0)return;const token=`${game.date}-${game.deadline}-${game.index}`;if(settings.sound&&endedSound.current!==token){endedSound.current=token;beep(false);}setGame(g=>{if(!g||g.rounds[g.index].complete)return g;return {...g,deadline:null,remaining:0,rounds:g.rounds.map((r,i)=>i===g.index?{...r,complete:true,timedOut:true,earned:0}:r)};});},[game,round,seconds,settings.sound]);
 const total=game?.rounds.reduce((sum,r)=>sum+r.earned,0)??0;const correct=game?.rounds.filter(r=>r.complete&&r.selected===r.playerId).length??0;
 function start(){unlock();setGame(newGame(settings.count,settings.duration));setNow(Date.now());setPage('game');}
 function pause(){setGame(g=>g?{...g,remaining:remainingTime(g),deadline:null}:g);}
 function home(){pause();setPage('home');}
 function updateRound(fn:(r:Round)=>Round){setNow(Date.now());setGame(g=>g?(g.deadline!==null&&remainingTime(g)===0?g:{...g,rounds:g.rounds.map((r,i)=>i===g.index?fn(r):r)}):g);}
 function answer(id:string){if(!round||round.complete||!game)return;if(game.deadline!==null&&remainingTime(game)===0){setNow(Date.now());return;}unlock();if(settings.sound)beep(id===round.playerId);setGame(g=>{if(!g||g.rounds[g.index].complete)return g;if(g.deadline!==null&&remainingTime(g)===0)return {...g,deadline:null,remaining:0,rounds:g.rounds.map((r,i)=>i===g.index?{...r,complete:true,timedOut:true,earned:0}:r)};return {...g,deadline:null,remaining:remainingTime(g),rounds:g.rounds.map((r,i)=>i===g.index?submit(r,id):r)};});}
 function next(){setGame(g=>{if(!g||!g.rounds[g.index].complete)return g;if(g.index===g.rounds.length-1)return {...g,finished:true,deadline:null};return {...g,index:g.index+1,remaining:g.duration,deadline:g.duration?Date.now()+g.duration*1000:null};});setNow(Date.now());}
 function exportRoster(){const url=URL.createObjectURL(new Blob([JSON.stringify(players,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='수원삼성-선수명단-20261009.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="football-shell"><header className="football-header"><button className="football-brand" onClick={home}><img src={assetPath('/images/suwon-bluewings-logo.png')} alt="수원삼성 블루윙즈 로고"/><span>누구게, 블루윙즈!</span></button><button className="icon-button" aria-label={settings.sound?'효과음 끄기':'효과음 켜기'} onClick={()=>{unlock();setSettings({...settings,sound:!settings.sound});}}>{settings.sound?<Volume2/>:<VolumeX/>}</button></header>
 {message&&<div role="status" className="football-notice">{message}<button onClick={()=>setMessage('')} aria-label="알림 닫기"><X size={16}/></button></div>}
 {page==='home'&&<main className="football-home"><div className="football-eyebrow">SUWON SAMSUNG BLUEWINGS</div><h1>얼굴 한 조각,<br/><em>우리 선수</em> 알아요?</h1><p className="football-lead">얼굴 64칸 중 딱 한 칸부터 시작!<br/>적은 힌트로 맞힐수록 점수가 높아져요!</p><div className="club-hero"><img src={assetPath('/images/suwon-bluewings-logo.png')} alt="수원삼성 엠블럼"/><span className="points-sticker">첫 도전<br/><b>100점</b></span></div><section className="football-setup"><label>몇 명을 맞혀 볼까요?</label><div className="football-segments">{[10,20,40].map(n=><button key={n} className={settings.count===n?'selected':''} onClick={()=>setSettings({...settings,count:n})}>{n===40?'전체 40':n}<small>명</small></button>)}</div><label>한 문제당 제한시간</label><div className="football-segments small">{[0,30,60,90].map(n=><button key={n} className={settings.duration===n?'selected':''} onClick={()=>setSettings({...settings,duration:n})}>{n===0?'제한 없음':`${n}초`}</button>)}</div><p className="score-rule"><Lightbulb size={16}/>힌트마다 −15점 · 최저 10점 · 오답 0점</p></section><button className="football-primary" onClick={start}><Play size={18} fill="currentColor"/> 선수 맞히기 시작 <ArrowRight size={18}/></button>{game&&!game.finished&&<button className="football-secondary" onClick={()=>setPage('game')}>이어서 하기 · {game.index+1}번 문제</button>}<button className="football-link" onClick={()=>setPage('roster')}><Users size={18}/> 선수 도감 · {players.length}명</button><p className="football-footnote">선수 순서와 보기는 매 게임 새로 섞입니다.</p></main>}
 {page==='game'&&game&&(game.finished?<main className="football-results"><div className="football-trophy"><Trophy size={58}/></div><div className="football-eyebrow">오늘의 블루윙즈 팬 점수</div><h1>{total}<small>점</small></h1><p className="football-lead">{correct===game.rounds.length?'완벽한 팬심! 전부 맞혔어요.':'우리 선수들과 한 걸음 더 가까워졌어요!'}</p><div className="football-stats"><div><b>{correct}</b>정답</div><div><b>{game.rounds.filter(r=>r.complete&&r.selected!==r.playerId).length}</b>오답·시간 종료</div><div><b>{Math.round(correct/game.rounds.length*100)}%</b>정답률</div></div><p className="football-footnote">{game.rounds.length}문제 · 최대 {game.rounds.length*100}점 · 미응답 {game.rounds.filter(r=>!r.complete).length}문제</p><button className="football-primary" onClick={start}><RotateCcw size={18}/> 다시 도전하기</button><button className="football-secondary" onClick={home}>시작 화면으로</button><div className="round-review"><h2>오늘의 경기 기록</h2>{game.rounds.map((r,i)=><div key={r.playerId}><span>{i+1}. {byId.get(r.playerId)?.name}</span><span>{!r.complete?'미응답':r.timedOut?'시간 종료':r.selected===r.playerId?`+${r.earned}점`:'오답'}</span></div>)}</div></main>:round&&player&&<main className="football-play"><div className="round-top"><span>문제 <b>{game.index+1}</b> / {game.rounds.length}</span><button className="football-link" onClick={()=>{if(confirm('게임을 종료하고 결과를 볼까요?'))setGame({...game,finished:true,remaining:remainingTime(game),deadline:null});}}>게임 종료 <X size={15}/></button></div><div className="football-progress"><i style={{width:`${(game.index+1)/game.rounds.length*100}%`}}/></div><div className="score-bar"><span>누적 <b>{total}점</b></span><span>{round.complete?'획득 점수':'지금 맞히면'} <b>{round.complete?round.earned:availableScore(round)}점</b></span></div><PlayerPhoto player={player} stage={round.photoStage} tileOrder={round.tileOrder} full={round.complete}/><div className="revealed-hints" aria-live="polite">{round.hints.filter(h=>h!=='photo').map(h=><span key={h}>{h==='age'?`나이 · 만 ${age(player.birthday,game.date)}세`:h==='height'?`키 · ${player.height}cm`:`포지션 · ${positionNames[player.position]}`}</span>)}{!round.hints.length&&<p>얼굴의 작은 한 조각만 보고 골라 보세요!</p>}</div>
 {!round.complete&&<button className="hint-button" disabled={!availableHints(round).length} onClick={()=>updateRound(r=>addHint(r))}><Lightbulb size={19}/><span>{availableHints(round).length?'추가 힌트 · 무작위 공개':'모든 힌트를 공개했어요'}<small>{availableHints(round).length?`다음 정답 배점 ${Math.max(10,availableScore(round)-15)}점`:'이제 보기에서 골라 주세요'}</small></span><span className="hint-cost">{availableHints(round).length?availableScore(round)>10?'−15점':'최저 10점':''}</span></button>}
 {round.complete&&<div className={`football-answer ${round.selected===round.playerId?'correct':'incorrect'}`} role="status"><span>{round.timedOut?'시간 종료!':round.selected===round.playerId?`정답! +${round.earned}점`:'아쉽지만 오답이에요'}</span><h2>{player.name}</h2><Profile player={player} date={game.date}/></div>}
 <div className="choices" aria-label="선수 이름 보기">{round.choices.map((id,i)=><button key={id} disabled={round.complete} className={round.complete?(id===round.playerId?'right':id===round.selected?'wrong':''):''} onClick={()=>answer(id)}><span className="choice-number">{i+1}</span>{byId.get(id)?.name}{round.complete&&id===round.playerId&&<Check size={19}/>}</button>)}</div>
 <div className={`football-timer ${game.duration&&seconds<=10&&!round.complete?'urgent':''}`}><div><span>{game.duration===0?'천천히 생각해 보세요':round.complete?'문제 종료':'남은 시간'}</span>{game.duration>0&&<b role="timer">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</b>}</div>{game.duration>0&&!round.complete&&<button aria-label={game.deadline?'타이머 일시정지':'타이머 재개'} onClick={()=>{unlock();setNow(Date.now());if(game.deadline)pause();else setGame({...game,deadline:Date.now()+game.remaining*1000});}}>{game.deadline?<Pause size={16}/>:<Play size={16}/>} {game.deadline?'일시정지':'재개'}</button>}<button className="next-button" disabled={!round.complete} onClick={next}>{game.index===game.rounds.length-1?'결과 보기':'다음 선수'}<ArrowRight size={17}/></button></div><p className="football-footnote">한 번 선택하면 확정됩니다. 힌트는 중복되지 않아요.</p></main>)}
 {page==='roster'&&<main className="football-roster"><button className="football-link" onClick={home}><ArrowLeft size={17}/> 시작 화면</button><div className="roster-heading"><div><h1>우리 팀 선수 도감</h1><p>공식 선수단 40명 · 2026.10.09 수집</p></div><button className="icon-button" onClick={exportRoster} aria-label="선수 명단 JSON 내보내기"><Download size={20}/></button></div><label className="roster-search"><Search size={18}/><input aria-label="선수 이름 검색" placeholder="선수 이름으로 찾아보세요" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="position-filter">{['ALL','GK','DF','MF','FW'].map(pos=><button key={pos} className={filter===pos?'active':''} onClick={()=>setFilter(pos)}>{pos==='ALL'?'전체':positionNames[pos]} <small>{pos==='ALL'?players.length:players.filter(p=>p.position===pos).length}</small></button>)}</div><div className="roster-grid">{players.filter(p=>(filter==='ALL'||p.position===filter)&&p.name.includes(search.trim())).map(p=><article key={p.id}><PlayerPhoto player={p} stage={4} full/><div className="roster-info"><span>NO. {p.number}</span><h2>{p.name}</h2><Profile player={p} date={localDate()}/><p>{p.birthday} · {p.weight}kg</p></div></article>)}</div>{!players.some(p=>(filter==='ALL'||p.position===filter)&&p.name.includes(search.trim()))&&<p className="empty-roster">검색 결과가 없습니다. 다른 이름으로 검색해 주세요.</p>}<p className="football-footnote">출처: <a href="https://www.bluewings.kr/player/pro" target="_blank" rel="noreferrer">수원삼성 공식 선수단</a><br/>소속·프로필은 수집 시점 기준이며 이적 등에 따라 달라질 수 있습니다.</p></main>}
 <footer className="football-footer">SUWON BLUEWINGS <span>우리 팀을 알아가는 시간</span></footer></div>;
}
