import { describe,expect,it } from 'vitest';
import { comboStats,isNoHintCorrect,players,newGame,addHint,availableHints,availableScore,submit,age,remainingTime,validGame,FACE_TILES,elapsedMs,completeRound,gameRecord,rankRecords } from './player-game';
describe('선수 맞히기',()=>{
 it('오답은 15점 감소 후 같은 자리를 새 보기로 교체하고 타이머를 유지한다',()=>{const g=newGame(10);const r=g.rounds[0];const wrong=r.choices.find(id=>id!==r.playerId)!;const index=r.choices.indexOf(wrong);const retried=submit(r,wrong);expect(retried.complete).toBe(false);expect(retried.wrongIds).toEqual([wrong]);expect(retried.choices).not.toContain(wrong);expect(retried.choices).toHaveLength(4);expect(retried.choices[index]).not.toBe(wrong);expect(retried.choices).toContain(r.playerId);expect(availableScore(retried)).toBe(85);const next=completeRound(g,retried);expect(next.deadline).toBe(g.deadline);expect(next.completedAt).toBeNull();expect(submit(retried,wrong)).toBe(retried);expect(submit(retried,r.playerId).earned).toBe(85);});
 it('반복 오답은 재등장하지 않고 새 후보가 없으면 보기만 제외하며 최저 10점을 지킨다',()=>{let r=newGame(10).rounds[0];for(let i=0;i<39;i++){const wrong=r.choices.find(id=>id!==r.playerId)!;expect(wrong).toBeTruthy();r=submit(r,wrong);expect(new Set(r.choices).size).toBe(r.choices.length);for(const rejected of r.wrongIds)expect(r.choices).not.toContain(rejected);}expect(r.choices).toEqual([r.playerId]);expect(r.wrongIds).toHaveLength(39);expect(availableScore(r)).toBe(10);expect(submit(r,r.playerId).earned).toBe(10);});
 it('오답 횟수와 교체된 보기를 새로고침 후 복원할 수 있다',()=>{const g=newGame(10);const r=g.rounds[0];const updated=completeRound(g,submit(r,r.choices.find(id=>id!==r.playerId)!));const saved=JSON.parse(JSON.stringify(updated));expect(validGame(saved)).toBe(true);expect(saved.rounds[0].wrongIds).toHaveLength(1);expect(saved.rounds[0].choices).toEqual(updated.rounds[0].choices);});
 it('한 선수당 30초이며 일시정지 중에도 누적 시간은 흐른다',()=>{const g={...newGame(10),startedAt:1000,deadline:null};expect(g.duration).toBe(30);expect(g.remaining).toBe(30);expect(elapsedMs(g,7500)).toBe(6500);expect(elapsedMs({...g,endedAt:8000,finished:true},20000)).toBe(7000);expect(gameRecord({...g,endedAt:8000,finished:true})).toBeNull();});
 it('마지막 답 확정 때 완료 시간을 멈추고 결과 버튼 대기는 포함하지 않는다',()=>{const g={...newGame(10,'우리 팀'),startedAt:1000,index:9};g.rounds=g.rounds.map((r,i)=>i<9?submit(r,r.playerId):r);const done=completeRound(g,submit(g.rounds[9],g.rounds[9].playerId),9100);expect(done.completedAt).toBe(9100);expect(elapsedMs(done,20000)).toBe(8100);expect(gameRecord(done)).toMatchObject({name:'우리 팀',count:10,score:1000,elapsed:8100});expect(completeRound(done,done.rounds[9],25000)).toBe(done);});
 it('시간 종료가 늦게 감지돼도 실제 제한 종료 시각으로 완주를 기록한다',()=>{const g={...newGame(10),startedAt:1000,index:9,deadline:31000};g.rounds=g.rounds.map((r,i)=>i<9?submit(r,r.playerId):r);const done=completeRound(g,{...g.rounds[9],complete:true,timedOut:true},g.deadline);expect(elapsedMs(done,100000)).toBe(30000);});
 it('같은 문제 수에서 점수 우선, 동점은 밀리초 단위 빠른 시간 순으로 정렬한다',()=>{const base={name:'팀',date:'2026-10-09',count:10,score:500};const list=[{...base,id:'slow',elapsed:12345},{...base,id:'fast',elapsed:12344},{...base,id:'higher',score:501,elapsed:99999},{...base,id:'other',count:20,score:2000,elapsed:100}];expect(rankRecords(list,10).map(r=>r.id)).toEqual(['higher','fast','slow']);expect(list[0].id).toBe('slow');});
 it('처음 공개 칸이 얼굴 내부에 있으며 각 문제에 64칸 순서를 저장한다',()=>{for(const r of newGame(40).rounds){expect(r.tileOrder).toHaveLength(64);expect(new Set(r.tileOrder).size).toBe(64);const first=r.tileOrder[0];expect(Math.floor(first/8)).toBeGreaterThanOrEqual(3);expect(Math.floor(first/8)).toBeLessThanOrEqual(5);expect(first%8).toBeGreaterThanOrEqual(1);expect(first%8).toBeLessThanOrEqual(6);const next=addHint(r,0);expect(next.tileOrder).toBe(r.tileOrder);expect(next.photoStage).toBe(1);} });
 it('저장 상태의 공개 칸 순서가 유지되고 중복된 칸 순서를 거부한다',()=>{const g=newGame(10);const restored=JSON.parse(JSON.stringify(g));expect(validGame(restored)).toBe(true);expect(restored.rounds[0].tileOrder).toEqual(g.rounds[0].tileOrder);const corrupt={...g,rounds:g.rounds.map((r,i)=>i===0?{...r,tileOrder:Array(64).fill(0)}:r)};expect(validGame(corrupt)).toBe(false);});
 it('공식 40명과 고유 선수 ID, 사진과 얼굴 좌표가 있다',()=>{expect(players).toHaveLength(40);expect(new Set(players.map(p=>p.id)).size).toBe(40);for(const p of players){expect(p.face.eyeTop).toBeLessThan(p.face.eyeBottom);expect(p.face.eyeBottom).toBeLessThan(p.face.noseBottom);expect(p.face.noseBottom).toBeLessThan(p.face.mouthBottom);expect(p.image).toMatch(/^\/images\/players\//);}});
 it('모든 선수와 4개의 고유 보기를 중복 없이 출제한다',()=>{const g=newGame(40);expect(new Set(g.rounds.map(r=>r.playerId)).size).toBe(40);for(const r of g.rounds){expect(new Set(r.choices).size).toBe(4);expect(r.choices).toContain(r.playerId);}expect(validGame(g)).toBe(true);});
 it('사진은 한 칸씩 중복 없이 확장되고 정보 힌트는 한 번만 나온다',()=>{let r=newGame(10).rounds[0];for(let i=0;i<FACE_TILES-1;i++)r=addHint(r,0);expect(r.photoStage).toBe(63);expect(new Set(r.tileOrder.slice(0,r.photoStage+1)).size).toBe(64);expect(availableScore(r)).toBe(10);for(let i=0;i<3;i++)r=addHint(r,0);expect(new Set(r.hints.filter(h=>h!=='photo')).size).toBe(3);expect(availableHints(r)).toHaveLength(0);expect(addHint(r)).toBe(r);expect(availableScore(r)).toBe(10);});
 it('랜덤 선택으로 사진 또는 정보 힌트를 보여 준다',()=>{const r=newGame(10).rounds[0];expect(addHint(r,0).hints).toEqual(['photo']);expect(addHint(r,.3).hints).toEqual(['age']);expect(addHint(r,.6).hints).toEqual(['height']);expect(addHint(r,.9).hints).toEqual(['position']);});
 it('정답 배점과 재도전, 중복 제출 및 종료 후 힌트를 차단한다',()=>{const r=newGame(10).rounds[0];expect(submit(r,r.playerId).earned).toBe(100);const hinted=addHint(r,0);const done=submit(hinted,r.playerId);expect(done.earned).toBe(85);expect(submit(done,r.choices.find(id=>id!==r.playerId)!)).toBe(done);expect(addHint(done)).toBe(done);expect(submit(r,r.choices.find(id=>id!==r.playerId)!).earned).toBe(0);expect(submit(r,'unknown')).toBe(r);});
 it('만 나이를 생일 전후로 계산한다',()=>{expect(age('2000-10-10','2026-10-09')).toBe(25);expect(age('2000-10-09','2026-10-09')).toBe(26);});
 it('타이머 복구와 손상된 상태 검증',()=>{const g=newGame(10);expect(remainingTime({...g,deadline:10000},6500)).toBe(4);expect(remainingTime({...g,deadline:10000},11000)).toBe(0);expect(validGame({...g,index:99})).toBe(false);expect(validGame({...g,rounds:[g.rounds[0],g.rounds[0]]})).toBe(false);expect(validGame(null)).toBe(false);});
});

describe('콤보와 노힌트 배지',()=>{
 it('힌트를 써도 첫 시도 정답이면 콤보가 이어지고 미래 문제는 끊지 않는다',()=>{const g=newGame(10);g.rounds[0]=submit(g.rounds[0],g.rounds[0].playerId);g.rounds[1]=submit(addHint(g.rounds[1],0),g.rounds[1].playerId);expect(comboStats(g.rounds)).toEqual({current:2,best:2});expect(isNoHintCorrect(g.rounds[0])).toBe(true);expect(isNoHintCorrect(g.rounds[1])).toBe(false);});
 it('미완료 문제의 오답 즉시 콤보를 끊고 재도전 정답은 콤보에 포함하지 않는다',()=>{const g=newGame(10);for(let i=0;i<2;i++)g.rounds[i]=submit(g.rounds[i],g.rounds[i].playerId);const r=g.rounds[2];g.rounds[2]=submit(r,r.choices.find(id=>id!==r.playerId)!);expect(comboStats(g.rounds)).toEqual({current:0,best:2});g.rounds[2]=submit(g.rounds[2],r.playerId);expect(isNoHintCorrect(g.rounds[2])).toBe(true);expect(comboStats(g.rounds)).toEqual({current:0,best:2});g.rounds[3]=submit(g.rounds[3],g.rounds[3].playerId);expect(comboStats(g.rounds)).toEqual({current:1,best:2});});
 it('시간 종료와 미응답은 배지를 주지 않으며 종료는 콤보를 끊는다',()=>{const g=newGame(10);g.rounds[0]=submit(g.rounds[0],g.rounds[0].playerId);g.rounds[1]={...g.rounds[1],complete:true,timedOut:true};expect(comboStats(g.rounds)).toEqual({current:0,best:1});expect(isNoHintCorrect(g.rounds[1])).toBe(false);expect(isNoHintCorrect(g.rounds[2])).toBe(false);});
});
