import roster from './players.json';
export type Player = typeof roster[number];
export const players: Player[] = roster;
export const positionNames: Record<string,string> = {GK:'골키퍼',DF:'수비수',MF:'미드필더',FW:'공격수'};
export type Hint = 'photo' | 'age' | 'height' | 'position';
export const FACE_GRID = 8;
export const FACE_TILES = FACE_GRID * FACE_GRID;
export function tileOrder(){const all=Array.from({length:FACE_TILES},(_,i)=>i);const facial=all.filter(i=>Math.floor(i/FACE_GRID)>=3&&Math.floor(i/FACE_GRID)<=5&&i%FACE_GRID>=1&&i%FACE_GRID<=6);return [...shuffle(facial),...shuffle(all.filter(i=>!facial.includes(i)))];}
export type Round = { playerId: string; choices: string[]; photoStage: number; tileOrder:number[]; hints: Hint[]; selected: string | null; complete: boolean; earned: number; timedOut: boolean };
export type Game = { rounds: Round[]; index: number; duration: number; remaining: number; deadline: number | null; finished: boolean; date: string };
export function shuffle<T>(items:T[]):T[]{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function age(birthday:string,date:string){const birth=birthday.split('-').map(Number),today=date.split('-').map(Number);return today[0]-birth[0]-(today[1]<birth[1]||(today[1]===birth[1]&&today[2]<birth[2])?1:0);}
export function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function availableScore(round:Round){return Math.max(10,100-round.hints.length*15);}
export function availableHints(round:Round):Hint[]{if(round.complete)return [];return [...(round.photoStage<FACE_TILES-1?['photo' as const]:[]),...(['age','height','position'] as Hint[]).filter(h=>!round.hints.includes(h))];}
export function addHint(round:Round,random=Math.random()):Round{const candidates=availableHints(round);if(!candidates.length)return round;const hint=candidates[Math.min(candidates.length-1,Math.floor(Math.max(0,random)*candidates.length))];return {...round,hints:[...round.hints,hint],photoStage:round.photoStage+(hint==='photo'?1:0)};}
export function submit(round:Round,id:string):Round{if(round.complete||!round.choices.includes(id))return round;return {...round,selected:id,complete:true,earned:id===round.playerId?availableScore(round):0};}
export function remainingTime(game:Game,now=Date.now()){return game.deadline===null?game.remaining:Math.max(0,Math.ceil((game.deadline-now)/1000));}
export function newGame(count:number,duration:number):Game {const chosen=shuffle(players).slice(0,count);return {rounds:chosen.map(p=>{const similar=players.filter(q=>q.id!==p.id&&q.position===p.position);const distractors=shuffle(similar.length>=3?similar:players.filter(q=>q.id!==p.id)).slice(0,3);return {playerId:p.id,choices:shuffle([p.id,...distractors.map(q=>q.id)]),photoStage:0,tileOrder:tileOrder(),hints:[],selected:null,complete:false,earned:0,timedOut:false};}),index:0,duration,remaining:duration,deadline:duration?Date.now()+duration*1000:null,finished:false,date:localDate()};}
export function validGame(value:unknown):value is Game{if(!value||typeof value!=='object')return false;const g=value as Game;if(!Array.isArray(g.rounds)||!g.rounds.length||g.rounds.length>players.length||!Number.isInteger(g.index)||g.index<0||g.index>=g.rounds.length||![0,30,60,90].includes(g.duration)||!Number.isFinite(g.remaining)||g.remaining<0||(g.deadline!==null&&!Number.isFinite(g.deadline))||typeof g.finished!=='boolean'||!/^\d{4}-\d{2}-\d{2}$/.test(g.date))return false;return new Set(g.rounds.map(r=>r.playerId)).size===g.rounds.length&&g.rounds.every(r=>players.some(p=>p.id===r.playerId)&&Array.isArray(r.choices)&&r.choices.length===4&&new Set(r.choices).size===4&&r.choices.includes(r.playerId)&&r.choices.every(id=>players.some(p=>p.id===id))&&Number.isInteger(r.photoStage)&&r.photoStage>=0&&r.photoStage<FACE_TILES&&Array.isArray(r.tileOrder)&&r.tileOrder.length===FACE_TILES&&new Set(r.tileOrder).size===FACE_TILES&&r.tileOrder.every(t=>Number.isInteger(t)&&t>=0&&t<FACE_TILES)&&Array.isArray(r.hints)&&r.hints.every(h=>['photo','age','height','position'].includes(h))&&r.hints.filter(h=>h==='photo').length===r.photoStage&&['age','height','position'].every(h=>r.hints.filter(v=>v===h).length<=1)&&typeof r.complete==='boolean'&&typeof r.timedOut==='boolean'&&(r.selected===null||r.choices.includes(r.selected))&&Number.isFinite(r.earned)&&r.earned>=0&&r.earned<=100);}
